update husky

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -6,11 +6,10 @@ npm run prettier
 
 echo "Running ESLint before push..."
 npm run lint-app
-exit 0
-RESULT=$?
-
-if [ $RESULT -ne 0 ]; then
-  echo "Linting failed. Fix errors before pushing."
-  exit 1
-fi
+#RESULT=$?
+#
+#if [ $RESULT -ne 0 ]; then
+#  echo "Linting failed. Fix errors before pushing."
+#  exit 1
+#fi
 
